version: '1.0'
services:
  mysql:
    container_name: mysql_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: YourSampple_database
      MYSQL_ROOT_PASSWORD: